function data()
return {
	en = {
		["info_name"] = "Berlin Stadtbahn Viaduct Construction Eeasy - Basic Segmets",
		["info_desc"] = "Icemaster presents: assets, stations, depots and much more\n + 4 tracks viaduct construction helper\n + available from 1882",

		["name_0"] = "Bverlin Stadtbahn Viaduct Construction Eeasy - Basic Segmets",
		["desc_0"] = "Icemaster presents: assets, stations, depots and much more\n + 4 tracks viaduct construction helper\n + available from 1882",

		["name_set"] = "Stadtbahn Berlin Viaduct Construction",
		["desc_set"] = "Stadtbahn Berlin +  straight segments * +8m to +16m\n * tracks can be edited via the magic stick tool and track assets can be placed",
		["name_bridge"] = "Stadtbahn Viaduct Bridge Construction",
		["desc_bridge"] = "Stadtbahn Berlin + bridge segments * +8m to +16m\n * tracks can be edited via the magic stick tool and track assets can be placed",
		["name_switch"] = "Stadtbahn Viaduct Switch Construction",
		["desc_switch"] = "Stadtbahn Berlin + switch segments * +8m to +16m\n ATTENTION! Assets cant be placed on this modules and track types can't be changed manually, but once placed, this segment can be can be configured!",
		["name_stationconnect"] = "Stadtbahn Viaduct Station Connections",
		["desc_stationconnect"] = "Stadtbahn Berlin + station connection segments * 8m to +16m\n * tracks can be edited via the magic stick tool and track assets can be placed",

		["name_endings"] = "Stadtbahn Viaduct Endings Construction",
		["desc_endings"] = "Stadtbahn Berlin + ending segments * 0m to +16m\n * tracks can be edited via the magic stick tool and track assets can be placed",
		["name_shop"] = "Stadtbahn Viaduct Shop Construction",
		["desc_shop"] = "Stadtbahn Berlin + shop segments * only +8m\n * with plebs magneteer(s) with different comercial or workplace cappacities ",
		["name_busdepot"] = "Stadtbahn Street Depot Viaduct",
		["desc_busdepot"] = "Stadtbahn Berlin + bus/truck depot * +8m\n * tracks can be edited via the magic stick tool and track assets can be placed",
		["name_cargo"] = "Stadtbahn Cargo Im- & Export * BETA",
		["desc_cargo"] = "Stadtbahn Berlin + truck station * 80-100m segment * +8m\n * tracks can be edited via the magic stick tool and track assets can be placed",
		["name_asset"] = "Stadtbahn Viaduct Assets",
		["desc_asset"] = "Stadtbahn Berlin + viaduct assets for curve building at invisible bridges\n * snapable * with seperate railing and other optons",

		["name_s_tier"] = "Stadtbahn Viaduct * Station S-Bhf. Tiergarten BETA",
		["desc_s_tier"] = "Stadtbahn Berlin + simple viaduct station * +8m\n * Not many options here.\nIn or out? Go west or head eastward?.. \n *North ending of tracks can't be snapped to other segments and have to be connected manually.",

		["name_s_adjust"] = "Stadtbahn Viaduct * Adjustable S-Bahn Station",
		["desc_s_adjust"] = "Stadtbahn Berlin + adjustable viaduct station* +8m to +12m",

		["name_s_westkreuz"] = "S-Bahn Station Westkreuz",
		["desc_s_westkreuz"] = "Stadtbahn Berlin + crossing station for local service * +8m",

		["name_station_entrance"] = "Entrance",
		["name_station_entrance00"] = "East",
		["name_station_entrance01"] = "West",
		["name_station_entrance02"] = "Both",
		["name_station_entrance03"] = "Middle",

		["name_station_roof"] = "Roof",
		["name_station_roof00"] = "Old",
		["name_station_roof01"] = "Modern",



		["name_module_roof_10m"] = "S-Bahn Berlin Roof Modern BETA",
		["desc_module_roof_10m"] = "Modern station roof only for 10m(!) platforms with... stuff^^",


		["name_era"] = "Era",
		["name_eraA"] = "Historic",
		["name_eraB"] = "Post War",
		["name_eraC"] = "Modern",

		["name_length"] = "Segment Length (in m)",
		["name_layout"] = "Arches Widths (in m)",
		["name_layout0"] = "10/15/25 Mix",
		["name_layout1"] = "only 20",
		["name_layout2"] = "30/40 Mix",
		["name_layout3"] = "Test",
		["name_station_length"] = "Platform Length (in m)",
		["name_station_endings"] = "Station Endings",

		["name_content"] = "Arches Contents",
		["name_con0"] = "Open",
		["name_con1"] = "Simple",
		["name_con2"] = "Brick",
		["name_con3"] = "Concrete",
		["name_con4"] = "Mix",
		["name_con5"] = "Dark",
		["name_con6"] = "Garage",
		["name_con7"] = "Passway",
		["name_con8"] = "Glas",
		["name_con9"] = "Ads",
		["name_con10"] = "Light",
		["name_con11"] = "None (Track & Bridge Helper)",

		["name_content_new"] = "Arches Contents Mix",
		["name_con1new"] = "1",
		["name_con2new"] = "2",
		["name_con3new"] = "3",
		["name_con4new"] = "4",
		["name_con5new"] = "5",
		["name_con6new"] = "6",
		["name_con7new"] = "7",
		["name_con8new"] = "8",
		["name_con9new"] = "9",
		["name_con10new"] = "10",

		["name_shop_type"] = "Shop Type",
		["name_shop0"] = "for rent (35m)",
		["name_shop1"] = "Pub (15m)",
		["name_shop2"] = "Bistro (20m)",
		["name_shop3"] = "Restaurant (2x25m)",
		["name_shop4"] = "Hotel (2x30m)",
		["name_shop5"] = "Shelther (20m)",
		["name_shop6"] = "Club (40m)",
		["name_shop7"] = "... (30m)",
		["name_shop8"] = "Museum (4x20m)",
		["name_shop9"] = "Cinema (25m)",
		["name_shop10"] = "Books (2x20m)",
		["name_shop11"] = "Repair (3x30m)",
		["name_shop12"] = "(more to come..)",
		["name_persons"] = "Guests per Month",

		["name_align"] = "Align Terrain",
		["name_viaduct_height"] = "Height Viaduct (in m)",
		["name_viaduct_side"] = "Height Difference Street to Viaduct Basement (in m)",
		["name_spacing"] = "Viaduct Width & Spacing Of Tracks",
		["name_track_pass"] = "Track Type A - Southern Passing Tracks 1&2",
		["name_track"] = "Track Type B - Northern Local Tracks 3&4",
		["name_switchA"] = "Switch Side A",
		["name_switchB"] = "Switch Side B",
		["name_stationA"] = "Station Side A",
		["name_stationB"] = "Station Side B",
		["name_bridge_type"] = "Bridge Type and Length (in m)",
		["name_bridgeL"] = "Bridge Length (in m)",
		["name_bridgeSides"] = "Bridge Endings Expansions (2x in m)",
		["name_bridgeRailing"] = "Bridge Railing Type",
		["name_railing1"] = "A Standard",
		["name_railing2"] = "B Narrow (Default)",
		["name_railing3"] = "C Wide",
		["name_street_pos"] = "Street Position",
		["name_street_posA"] = "South",
		["name_street_posB"] = "North",
		["name_street_posC"] = "Both Sides",
		["name_street_posD"] = "Test",
		["name_street_type"] = "Street Type",
		["name_tram"] = "Tram track",
		["name_tram_e"] = "Electric",

		["name_depot"] = "Depot Direction",
		["name_depot0"] = "South",
		["name_depot1"] = "North",

		["name_cargo_dir"] = "Cargo Delivery Direction",
		["name_cargo_dir0"] = "North In",
		["name_cargo_dir1"] = "North Out",

		["name_asset_arch_width"] = "Arch (from 10m) & Railing Width",
		["name_asset_arch_type"] = "Arch Content",
		["name_asset_type"] = "Railing Asset",
		["name_asset_typeA"] = "A",
		["name_asset_typeB"] = "B",
		["name_asset_typeC"] = "C",
		["name_asset_typeD"] = "Concrete",
		["name_asset_typeE"] = "Noise Barrier",
		["name_asset_typeF"] = "Mast Base",
		["name_asset_typeG"] = "Glas",

		["name_asset_snap"] = "Snap Asset",
		["name_asset_snap1"] = "On Track",
		["name_asset_snap2"] = "On Terrain",
		["name_asset_ground"] = "Ground Texture",
		["name_asset_deeper"] = "Arch/ Block Depth 2,5x",
		["name_asset_scaleY"] = "Arch Width Scale (n %)",
		["name_asset_slope"] = "Arch Slope (in ‰)",
		["name_logo"] = "Logo",
		["name_logoB"] = "North Side",
		["name_logo2"] = "Both Sides",
		["name_clock"] = "Clock",
		["name_ad1"] = "Ad1",
		["name_ad2"] = "Ad2",
		["name_ad3"] = "Ad3",
		["name_ad4"] = "Ad4",
		["name_ad5"] = "Ad5",

		["name_ending"] = "Layout Ending (Widen Between Tracks)",
		["name_ending0"] = "Dam",
		["name_ending1"] = "Bridge",
		["name_ending2"] = "Widen Tracks",
		["name_ending3"] = "-",
				
		},

	de = {
		["Brick"] = "Ziegel",

		["info_name"] = "Berlin Stadtbahn Viadukt Eeasy Bastelset - Basis Segmente",
		["info_desc"] = "Icemaster präsentiert: 4 Gleise Viadukt Bauhilfe\n + Assets, Bahnhöfe, Depots und vieles mehr\n + verfügbar ab 1882",
				
		["name_set"] = "Berlin Stadtbahn Viadukt Bastelset",
		["desc_set"] = "Stadtbahn Berlin * Geradensegmente * +8m bis +16m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",
		["name_bridge"] = "Stadtbahn Viadukt Bückenbau",
		["desc_bridge"] = "Stadtbahn Berlin * Brückensegmente * +8m bis +16m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",
		["name_switch"] = "Stadtbahn Viadukt Weichensetzung",
		["desc_switch"] = "Stadtbahn Berlin * Weichensegmente * +8m bis +16m\n *ACHTUNG! Assets und Gleistypen können in diesen Modulen nicht manuell geändert, dafür aber konfiguriert werden, wenn das Segment gesetz wurde!",
		["name_stationconnect"] = "Stadtbahn Viaduct Bahnhofsverbindungen",
		["desc_stationconnect"] = "Stadtbahn Berlin +  Bahnhofstrompeten * 8m to +16m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",

		["name_endings"] = "Stadtbahn Viadukt Endstücke",
		["desc_endings"] = "Stadtbahn Berlin * Endsegmente * 0m bis +16m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",
		["name_shop"] = "Stadtbahn Viadukt Ladenerstellung",
		["desc_shop"] = "Stadtbahn Berlin * Ladensegmente * nur +8m\n * mit Besuchermagnet(en) mit verschiedenen Kundenaufkommen oder Arbeitsplätzen ",
		["name_busdepot"] = "Stadtbahn Fahrzeugdepot Viadukt",
		["desc_busdepot"] = "Stadtbahn Berlin * Truck Depot * 25-75m Segment * +8m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",
		["name_cargo"] = "Stadtbahn Cargo Im- & Export * BETA",
		["desc_cargo"] = "Stadtbahn Berlin + LKW Station * +8m\n * Gleistypen können mit dem Zauberstab verändert werden und Track Assets sind platzierbar",
		["name_asset"] = "Stadtbahn Viadukt Assets",
		["desc_asset"] = "Stadtbahn Berlin + Viadukt Assets zum Kurvenvenbauen an unsichtbaren Brücken\n * einfach anzusanppen * mit unabhängigem Geländer und anderen Optionen",

		["name_s_tier"] = "Stadtbahn Viadukt * S-Bahnhof Tiergarten BETA",
		["desc_s_tier"] = "Stadtbahn Berlin + einfache Durchgangsstation * +8m\n * Viel kann man hier nicht machen.\nRein oder raus? Westwärts oder nach dem Osten?..\n *Nördliche Gelisenden sind nicht an andere Segmente asnappbar und müssen daher manuell angebunden werden.",

		["name_s_adjust"] = "Stadtbahn Viadukt * Einstellbare S-Bahn Station",
		["desc_s_adjust"] = "Stadtbahn Berlin + einstellbare Durchgangsstation * +8m bis +12m",

		["name_s_westkreuz"] = "S-Bahn Bahnhof Westkreuz",
		["desc_s_westkreuz"] = "Stadtbahn Berlin + Kreuzungsbahnhof der S-Bahn * +8m",

		["name_station_entrance"] = "Zugang",
		["name_station_entrance00"] = "Ost",
		["name_station_entrance01"] = "West",
		["name_station_entrance02"] = "Beide",
		["name_station_entrance03"] = "Mitte",


		["name_station_roof"] = "Dach",
		["name_station_roof00"] = "Alt",
		["name_station_roof01"] = "Modern",


		["name_asset_roof_10m"] = "S-Bahn Berlin Dach Modern BETA",
		["desc_asset_roof_10m"] = "Modernes Bahnhofsdach nur für 10m(!) Plattformen mit... Zeugs^^",


		["name_era"] = "Era",
		["name_eraA"] = "Historisch",
		["name_eraB"] = "Nachkrieg",
		["name_eraC"] = "Modern",

		["name_length"] = "Segment Länge (in m)",
		["name_layout"] = "Bögen Breiten (in m)",
		["name_layout0"] = "10/15/25 Mix",
		["name_layout1"] = "nur 20",
		["name_layout2"] = "30/40 Mix",
		["name_layout3"] = "Test",
		["name_station_length"] = "Platform Länge (in m)",
		["name_station_endings"] = "Bahnhofstrompeten",

		["name_content"] = "Bögen Inhalte",
		["name_con0"] = "Offen",
		["name_con1"] = "Einfach",
		["name_con2"] = "Ziegel",
		["name_con3"] = "Beton",
		["name_con4"] = "Gemischt",
		["name_con5"] = "Dunkel",
		["name_con6"] = "Garage",
		["name_con7"] = "Durchgang",
		["name_con8"] = "Glas",
		["name_con9"] = "Werbung",
		["name_con10"] = "Licht",
		["name_con11"] = "Keine (Gleis- und Brückenhilfe)",

		["name_content_new"] = "Bögen Inhalte Mix",
		["name_con1new"] = "1",
		["name_con2new"] = "2",
		["name_con3new"] = "3",
		["name_con4new"] = "4",
		["name_con5new"] = "5",
		["name_con6new"] = "6",
		["name_con7new"] = "7",
		["name_con8new"] = "8",
		["name_con9new"] = "9",
		["name_con10new"] = "10",

		["name_shop_type"] = "Ladentyp",
		["name_shop0"] = "zu vermieten (35m)", -- Bushido
		["name_shop1"] = "Kneipe (15m)", --Besenkammer
		["name_shop2"] = "Bistro (20m)", -- MoabEat
		["name_shop3"] = "Restaurant (2x25m)", -- BBQ
		["name_shop4"] = "Hotel (2x30m)",
		["name_shop5"] = "Mission (20m)", -- Bahnhofsmission
		["name_shop6"] = "Club (25m)", -- sound..
		["name_shop7"] = "Biergarten (35m)", -- Hooters 3 Bögen
		["name_shop8"] = "Museum (4x20m)", --Buchstaben? Motorrad?
		["name_shop9"] = "Kino (25m)", -- ?
		["name_shop10"] = "Bücher (2x20m)", -- Savigny..
		["name_shop11"] = "Werkstatt (3x30m)", --AutoAuto
		["name_shop12"] = "(mehr folgen..)",
		["name_persons"] = "Gäste pro Monat",

		["name_align"] = "Gelände ebnen",
		["name_viaduct_height"] = "Höhe Viadukt (in m)",
		["name_viaduct_side"] = "Höhenunterschied Strasse zur Viaduktbasis (in m)",
		["name_spacing"] = "Viadukt Breite & Gleisabstände",
		["name_track_pass"] = "Gleistyp A - Fernbahn - südliche  Gleise 1&2",
		["name_track"] = "Gleistyp B - S-Bahn - nördliche Gleise 3&4",
		["name_switchA"] = "Weiche Seite A",
		["name_switchB"] = "Weiche Seite B",
		["name_stationA"] = "Aufweitung Seite A",
		["name_stationB"] = "Aufweitung Seite B",
		["name_bridge_type"] = "Brücke Typ und Länge (in m)",
		["name_bridgeL"] = "Brücke Länge (in m)",
		["name_bridgeSides"] = "Brückenenden Erweiterungen (in m)",
		["name_bridgeRailing"] = "Brücke Geländer",
		["name_railing1"] = "A Standard",
		["name_railing2"] = "B Eng (Default)",
		["name_railing3"] = "C Weit",
		["name_street_pos"] = "Strasse",
		["name_street_posA"] = "Süden",
		["name_street_posB"] = "Norden",
		["name_street_posC"] = "Beide Seiten",
		["name_street_posD"] = "Test",
		["name_street_type"] = "Strassentyp",
		["name_tram"] = "Strassenbahngleise",
		["name_tram_e"] = "Elektrisch",


		["name_track_west"] = "Gleistyp",


		["name_depot"] = "Depot Richtung",
		["name_depot0"] = "Süden",
		["name_depot1"] = "Norden",

		["name_cargo_dir"] = "Richtung Anlieferung",
		["name_cargo_dir0"] = "Nordzufahrt",
		["name_cargo_dir1"] = "Nordausfahrt",


		["name_asset_arch_width"] = " Bogen (ab 10m) & Geländer Länge",
		["name_asset_arch_type"] = "Bogen Inhalt",
		["name_asset_type"] = "Geländer Asset",
		["name_asset_typeA"] = "A",
		["name_asset_typeB"] = "B",
		["name_asset_typeC"] = "C",
		["name_asset_typeD"] = "Beton",
		["name_asset_typeE"] = "Schallschutz",
		["name_asset_typeF"] = "Mastbasis",
		["name_asset_typeG"] = "Glas",

		["name_asset_snap"] = "Snap Asset",
		["name_asset_snap1"] = "Am Gleis",
		["name_asset_snap2"] = "Gelände ebnen",
		["name_asset_ground"] = "Bodentextur",
		["name_asset_deeper"] = "Bogen/ Block Tiefe 2,5x",
		["name_asset_scaleY"] = "Bogen Skalierung Breite (in %)",
		["name_asset_slope"] = "Bogen Steigung (in ‰)",
		["name_logo"] = "Logo",
		["name_logoB"] = "Nordseite",
		["name_logoAB"] = "Beide Seiten",
		["name_clock"] = "Uhr",
		["name_ad1"] = "Werbung1",
		["name_ad2"] = "Werbung2",
		["name_ad3"] = "Werbung3",
		["name_ad4"] = "Werbung4",
		["name_ad5"] = "Werbung5",

		["name_ending"] = "Layout Endstück",
		["name_ending0"] = "Damm",
		["name_ending1"] = "Brücke",
		["name_ending2"] = "Aufweiten",
		["name_ending3"] = "-",
		
		},
	}
end