local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local jidutil = require "jan-invisible_dam"

function data()
	return { 
		availability = { yearFrom = 0, yearTo = 0, },
		cost = { price = 0, },
		description = {
			name = _("Left Invisible Dam"),
			description = _("Left invisible dam for elevated stations.\nUse N and M to cycle through predefined heights."),
			icon = "ui/construction/station/rail/modular_station/submerged_entrance-left-blank.tga"
		}, 
		category = {
			categories = { "Invisible Dam", },
		},
		type = "passenger_platform",
		order = {
			value = 700,
		},
		metadata = {
			platform = true,
		},
		updateFn = jidutil.CreateUpdateFn("left"),
		getModelsFn = jidutil.CreateGetModelsFn("left")
	}
end